title: Ouaisfi·eu · Contact
description: Porte d’entrée du projet
remote_theme: just-the-docs/just-the-docs
logo: /assets/logo.svg
color_scheme: light

# Options Just the Docs
search_enabled: true
back_to_top: true
back_to_top_text: "Retour en haut"

# Footers
footer_content: "© 2025 – Ouaisfi·eu • ‘Tout est permis sauf usage commercial’"

collections:
  kits:
    output: true

just_the_docs:
  collections:
    kits:
      name: "Kits Obsidian"  # libellé dans la navigation
      nav_fold: true         # navigation repliable (pratique si tu as beaucoup de kits)
      # search_exclude: false
search_enabled: true
